### ISSUE TITLE
[Bug] CI/CD 빌드 실패오류 수정

### ISSUE THREAD

**Issue by HSSJW** [7-umc-GrowIT/GrowIT-SpringBoot#100]
## 📝 작업 내용 설명
>  CI/CD 빌드 실패오류 수정

## ✅ 작업할 내용
- [ ] dev_deploy.yml파일 수정
```
      # 5. Gradle을 사용하여 프로젝트 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test  # gradle build 명령 실행
```

## 🙋🏻 참고 자료
> X
